### PR TITLE
Update OP Template

### PR DESCRIPTION
**Pull request by calebcabob**

### CODE REVIEW

**Comment by javelinanddart** [comment]
why is [/CENTER] removed?

**Comment by calebcabob** [comment]
Its so that the whole document is centered - it was set to be centered in 2 separate spots...leaving features and changelog uncentered - sooo, I made the whole thing just centered once

**Comment by IronSharpensIron2717** [comment]
Because it belongs at the end, #shipit

**Comment by calebcabob** [comment]
thank u
:P

**Comment by cuzz1369** [comment]
I don't want it all centered.

**Pull request merged**
