### PR TITLE
add support for Yu Yuphoria

### PR DESCRIPTION
**Pull request by pranav01**

### CODE REVIEW

**Comment by Meninblack007** [comment]
No Need To Add Download Link Because Its Not Official :-1:

**Comment by pranav01** [comment]
Im making it official -_- !!

**Comment by ghost** [comment]
then your device need to be there https://github.com/CandyRoms/vendor_candy/blob/c5.1/vendorsetup.sh and there https://github.com/CandyDevices/local_manifests

**Comment by cuzz1369** [comment]
And be sure NOT to duplicate anything that is in the manifest already e.g.
common files/kernels

**Comment by neohackt** [comment]
I have already made it for yuphoria and providing support for yureka :)

**Pull request closed without merging**
